title: ETHRio
email: hus@ethrio.org
description: >- # this means to ignore newlines until "baseurl:"
  March, 2022  
baseurl: "https://ethrio.github.io/ethrio.org" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: eth_rio
github_username:  drhus

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - sass
  - jekyll-sass-converter

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
